name: astroarch_interface
description: "Astroarch Interface - Remote observatory control. Zarletti-Osservatorio Jupiter."
publish_to: 'none'
version: 0.2.12+25

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
  min_sdk_android: 21
